logo: ./media/headshots/default.jpg

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: george_poole.tex

sphinx: 
  config: 
    html_theme_options: 
      use_download_button: false
